### ISSUE TITLE
Crash with code 254

### ISSUE THREAD

**Issue by tekand** [e-conomic/graphicsmagick-stream#10]
Hi,

I tried to use graphicsmagick-stream to convert PDF file to png (one page at a time), but I have run into the following error (also the same comes with the example.js):

```
[tekand@host graphicsmagick-stream]$ node example.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: graphicsmagick crashed with code: 254
    at ChildProcess.<anonymous> (/home/tekand/test_pdf_img/node_modules/graphicsmagick-stream/index.js:135:17)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

I have found no information about this error.

node v0.12.3
graphicsmagick 1.3.22-1
imagemagick 6.9.2.4-1
graphicsmagick-stream 2.1.2

Thank you in advance.

**Comment by ankitrshah89** [comment]
@tekand I am running into the same issue. Did you find a solution to this?

**Comment by ankitrshah89** [comment]
For anyone who gets the same issue, verify that the input pdf file is not corrupt and adheres to pdf standards like including the headers etc.

**Comment by NicolaPrenna** [comment]
For anyone using centOS 7, i resolved installing these libraries:
`yum install libpng libjpeg libpng-devel libjpeg-devel ghostscript libtiff libtiff-devel freetype freetype-devel jasper jasper-devel`

obviously I've installed them as root user
