### ISSUE TITLE
Add support for CentOS

### ISSUE THREAD

**Issue by jhihn** [e-conomic/graphicsmagick-stream#9]
Package will not install on any RedHat based distros.

**Comment by jhihn** [comment]
This seems to be satisfied by documenting:
sudo yum install GraphicsMagick-devel libarchive-devel

**Comment by ankitrshah89** [comment]
@jhihn I am trying to use graphicsmagick-stream on centos 7 as well.
I did manage to install the package successfull, but I get the following error: 

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: graphicsmagick crashed with code: 127
    at ChildProcess.<anonymous> (/srv/package/node_modules/graphicsmagick-stream/index.js:135:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

The source file is pretty simple:

var gm = require('graphicsmagick-stream');
var fs = require('fs');

var convert = gm({
  pool: 1,
  format: 'png'
});

fs.createReadStream(__dirname + '/../../pdfs/sample.pdf').pipe(convert({})).pipe(fs.createWriteStream(__dirname + '/../../pdfs/new.png'));
